# Generated by Django 6.0.5 on 2026-05-28 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama barang / alat sekolah', max_length=255)),
                ('category', models.CharField(help_text='Kategori barang (misal: Elektronik, Olahraga, Seni)', max_length=100)),
                ('serial_number', models.CharField(help_text='Nomor seri unik barang', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Maintenance'), ('broken', 'Broken')], default='available', help_text='Status ketersediaan barang', max_length=15)),
                ('description', models.TextField(blank=True, help_text='Deskripsi kondisi atau detail barang', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Tanggal mulai peminjaman')),
                ('end_date', models.DateField(help_text='Tanggal selesai peminjaman')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='pending', help_text='Status persetujuan peminjaman oleh Admin', max_length=15)),
                ('admin_note', models.TextField(blank=True, help_text='Catatan peninjauan dari Admin (misal: Alasan Reject/Approve)', null=True)),
                ('asset', models.ForeignKey(help_text='Aset yang dipinjam', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='assets.asset')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
